<a href="https://colab.research.google.com/github/KulsoomBibi/DataScienceWithAtomCamp/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1D Array

In [3]:
np.array([11, 12, 13, 14, 15])

array([11, 12, 13, 14, 15])

In [4]:
x = np.array([11, 12, 13, 14, 15])
x

array([11, 12, 13, 14, 15])

In [5]:
x[::2]

array([11, 13, 15])

In [6]:
x[::1]

array([11, 12, 13, 14, 15])

In [7]:
np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9],
    [11, 12, 13, 14]
    ])

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [8]:
A = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9],
    [11, 12, 13, 14]
    ])
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [9]:
A[1][2]

8

In [10]:
A[1,2]

8

In [11]:
A[1, ::2]

array([6, 8])

In [12]:
A[1, 1:2]

array([7])

In [13]:
A[:2, :2]

array([[1, 2],
       [6, 7]])

In [14]:
A.shape

(3, 4)

In [15]:
A.size

12

In [16]:
A.ndim#dimensions

2

In [17]:
A.dtype

dtype('int64')

In [18]:
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [19]:
A[2] = 100
A

array([[  1,   2,   3,   4],
       [  6,   7,   8,   9],
       [100, 100, 100, 100]])

In [20]:
A[2]= np.array([10, 20, 30, 400])
A

array([[  1,   2,   3,   4],
       [  6,   7,   8,   9],
       [ 10,  20,  30, 400]])

In [21]:
B = np.array([A, A, A])
B

array([[[  1,   2,   3,   4],
        [  6,   7,   8,   9],
        [ 10,  20,  30, 400]],

       [[  1,   2,   3,   4],
        [  6,   7,   8,   9],
        [ 10,  20,  30, 400]],

       [[  1,   2,   3,   4],
        [  6,   7,   8,   9],
        [ 10,  20,  30, 400]]])

In [22]:
B.shape

(3, 3, 4)

In [23]:
B.ndim

3

In [24]:
C = np.array([B, B])
C

array([[[[  1,   2,   3,   4],
         [  6,   7,   8,   9],
         [ 10,  20,  30, 400]],

        [[  1,   2,   3,   4],
         [  6,   7,   8,   9],
         [ 10,  20,  30, 400]],

        [[  1,   2,   3,   4],
         [  6,   7,   8,   9],
         [ 10,  20,  30, 400]]],


       [[[  1,   2,   3,   4],
         [  6,   7,   8,   9],
         [ 10,  20,  30, 400]],

        [[  1,   2,   3,   4],
         [  6,   7,   8,   9],
         [ 10,  20,  30, 400]],

        [[  1,   2,   3,   4],
         [  6,   7,   8,   9],
         [ 10,  20,  30, 400]]]])

In [25]:
C.shape

(2, 3, 3, 4)

In [26]:
C.ndim

4

In [27]:
A = np.array([
    [1, 2, 3, 4],
    [6, 7, 8, 9],
    [11, 12, 13, 14]
    ])
A

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [28]:
A.sum()#row-wise

90

In [29]:
A.sum(axis=0) #column-wise

array([18, 21, 24, 27])

In [30]:
A.sum(1)

array([10, 30, 50])

In [31]:
A.sum(0)

array([18, 21, 24, 27])

In [32]:
A.std()

4.232808366400098

In [33]:
A.var()

17.916666666666668

In [34]:
A.mean()

7.5

In [35]:
A.min()

1

In [36]:
A.max()

14

In [37]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

In [38]:
a + b

array([11, 22, 33, 44, 55])

In [39]:
a * b

array([ 10,  40,  90, 160, 250])

In [40]:
a + 1

array([2, 3, 4, 5, 6])

In [41]:
a * 1

array([1, 2, 3, 4, 5])

In [42]:
a += 1
a

array([2, 3, 4, 5, 6])

In [43]:
c = np.random.rand(2 , 4)
c

array([[0.75425783, 0.33031846, 0.91487961, 0.98054279],
       [0.26838549, 0.65133171, 0.42134249, 0.20918021]])

In [44]:
np.random.rand(5)

array([0.89353812, 0.12032944, 0.55490633, 0.62272813, 0.89065953])

In [45]:
c = np.random.rand(2 , 5)# two rows and five cloumns
c

array([[0.23286897, 0.2275551 , 0.05104107, 0.37027794, 0.07588613],
       [0.98495137, 0.72752529, 0.35799145, 0.09686801, 0.10084885]])

In [46]:
np.random.rand(2, 5, 3)

array([[[0.53173208, 0.50836384, 0.01805332],
        [0.12995364, 0.3644458 , 0.72899411],
        [0.84804777, 0.89854543, 0.9068923 ],
        [0.12823307, 0.95830887, 0.66579806],
        [0.71478196, 0.89668914, 0.48550061]],

       [[0.56194405, 0.96721849, 0.99678685],
        [0.8534858 , 0.12746799, 0.33372224],
        [0.23389736, 0.17254877, 0.94923161],
        [0.39240363, 0.93138985, 0.05173119],
        [0.55417439, 0.20897829, 0.69229603]]])

In [47]:
c = np.random.randn(2 , 5)
c

array([[-0.4183589 ,  0.21496944,  1.40798142,  0.61840989, -1.53617945],
       [-0.49981614,  1.25182248, -1.80805114,  0.60748053, -1.39707869]])

In [48]:
np.random.randint(100, size=(2, 5))

array([[52, 33, 21, 33,  2],
       [94, 33, 94, 50, 65]])

In [49]:
arr = np.random.randint(90, 100, size=(2, 4))
arr

array([[98, 91, 94, 91],
       [97, 99, 97, 91]])

In [50]:
arr.reshape(2, 2, 2)

array([[[98, 91],
        [94, 91]],

       [[97, 99],
        [97, 91]]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [54]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [55]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [61]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [62]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [63]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [66]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.eye(3, 3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])